// STRATA — project data. All names, figures and prices are fictional (concept project).

export const MASTER = { w: 2688, h: 1520 }

// Building bounds inside the master image (px) — used for layout fitting
export const BUILDING_BOX = { x: 886, y: 196, w: 884, h: 1090 }

// Floors, ordered bottom → top. `slice` = rect of the floor inside the master image.
export const FLOORS = [
  {
    id: 'g',
    label: 'G',
    num: '00',
    name: 'The Plinth',
    kind: 'Lobby & Amenities',
    elevation: '±0.00',
    hour: '18:20',
    light: 'Evening lamplight',
    material: 'Basalt & bronze',
    slice: { x: 900, y: 1085, w: 860, h: 197 },
    facade: 'facade-g',
    teaser: 'Double-height lobby, concierge, residents’ lounge',
    intro:
      'A dark basalt plinth anchors the building to the riverbank. Inside, a double-height hall gathers around a still reflecting pool and a single birch — the threshold between city and home.',
    specs: [
      ['Ceiling', '6.2 m'],
      ['Concierge', '24 / 7'],
      ['Wellness', 'Spa & sauna'],
      ['Parking', '32 bays · EV'],
      ['Bicycle', 'Atelier'],
      ['Garden', '1,400 m²'],
    ],
    price: 'Residents only',
    features: ['Reflecting pool & birch court', 'Residents’ lounge & library', 'Finnish sauna, cold plunge', 'Private dining room', 'Parcel & cold storage'],
    palette: [['Basalt', '#2b2a28'], ['Travertine', '#cbbda6'], ['Bronze', '#8a6a46'], ['Birch', '#e8e3d8']],
    zones: [
      { id: 'lobby', name: 'Lobby', img: 'g-lobby' },
      { id: 'garden', name: 'Garden', img: 'landscape' },
    ],
    plan: {
      rooms: [
        { x: 0, y: 0, w: 62, h: 40, label: 'Lobby', area: '168 m²', zone: 'lobby' },
        { x: 62, y: 0, w: 38, h: 18, label: 'Lounge', area: '64 m²' },
        { x: 62, y: 18, w: 18, h: 22, label: 'Concierge', area: '22 m²' },
        { x: 80, y: 18, w: 20, h: 22, label: 'Wellness', area: '48 m²' },
        { x: 0, y: 40, w: 30, h: 20, label: 'Dining', area: '38 m²' },
        { x: 30, y: 40, w: 22, h: 20, label: 'Cores', area: '' },
        { x: 52, y: 40, w: 48, h: 20, label: 'Bicycle atelier', area: '56 m²' },
      ],
      outdoor: [{ x: 0, y: 60, w: 100, h: 16, label: 'Reflecting pool · Birch garden', zone: 'garden' }],
      pool: { x: 18, y: 10, w: 26, h: 14 },
    },
  },
  {
    id: '01',
    label: '01',
    num: '01',
    name: 'Garden Residences',
    kind: 'Two-bedroom residences',
    elevation: '+4.20',
    hour: '07:40',
    light: 'Morning mist',
    material: 'White oak & linen',
    slice: { x: 876, y: 950, w: 908, h: 135 },
    facade: 'facade-01',
    teaser: '86 m² · 2 bedrooms · private garden',
    intro:
      'Closest to the ground and the birches. White oak, linen and soft lime walls open onto a private garden court that holds the morning mist off the river.',
    specs: [
      ['Area', '86 m²'],
      ['Bedrooms', '2'],
      ['Bathrooms', '2'],
      ['Garden', '38 m²'],
      ['View', 'Birch court'],
      ['Residences', '4'],
    ],
    price: 'From €318,000',
    features: ['Private garden court', 'Underfloor heating', 'Floor-to-ceiling glazing', 'Oak joinery throughout'],
    palette: [['White oak', '#c9a97f'], ['Linen', '#e6dccb'], ['Lime plaster', '#efe9df'], ['Moss', '#6f7454']],
    zones: [
      { id: 'living', name: 'Living', img: '01-living' },
      { id: 'bedroom', name: 'Bedroom', img: '01-bedroom' },
    ],
    plan: {
      rooms: [
        { x: 0, y: 0, w: 52, h: 36, label: 'Living / Dining', area: '34 m²', zone: 'living' },
        { x: 52, y: 0, w: 20, h: 22, label: 'Kitchen', area: '9 m²', zone: 'living' },
        { x: 72, y: 0, w: 28, h: 30, label: 'Bedroom', area: '15 m²', zone: 'bedroom' },
        { x: 72, y: 30, w: 28, h: 30, label: 'Bedroom 2', area: '12 m²' },
        { x: 52, y: 22, w: 20, h: 16, label: 'Bath', area: '6 m²' },
        { x: 52, y: 38, w: 20, h: 22, label: 'Entry', area: '7 m²' },
        { x: 0, y: 36, w: 52, h: 24, label: 'Study / Wardrobe', area: '9 m²' },
      ],
      outdoor: [{ x: 0, y: 60, w: 100, h: 18, label: 'Private garden · 38 m²', zone: 'living' }],
    },
  },
  {
    id: '02',
    label: '02',
    num: '02',
    name: 'Linen Residences',
    kind: 'Two-bedroom + study',
    elevation: '+7.60',
    hour: '11:30',
    light: 'Soft overcast noon',
    material: 'Lime plaster & linen',
    slice: { x: 876, y: 815, w: 908, h: 135 },
    facade: 'facade-02',
    teaser: '96 m² · 2 bedrooms + study · loggia',
    intro:
      'The quietest light in the building. Breathable lime-plaster walls, linen and pale oak are tuned for the even, silver daylight of a northern noon.',
    specs: [
      ['Area', '96 m²'],
      ['Bedrooms', '2 + study'],
      ['Bathrooms', '2'],
      ['Loggia', '11 m²'],
      ['View', 'River'],
      ['Residences', '4'],
    ],
    price: 'From €392,000',
    features: ['Glazed loggia to the river', 'Travertine island kitchen', 'Lime-plaster walls', 'Walk-in wardrobe'],
    palette: [['Lime plaster', '#ece6dc'], ['Linen', '#ddd3c2'], ['Pale oak', '#d2b892'], ['Travertine', '#d8ccb7']],
    zones: [
      { id: 'living', name: 'Living', img: '02-living' },
      { id: 'kitchen', name: 'Kitchen', img: '02-kitchen' },
    ],
    plan: {
      rooms: [
        { x: 0, y: 0, w: 46, h: 38, label: 'Living / Dining', area: '36 m²', zone: 'living' },
        { x: 46, y: 0, w: 22, h: 24, label: 'Kitchen', area: '11 m²', zone: 'kitchen' },
        { x: 68, y: 0, w: 32, h: 28, label: 'Bedroom', area: '16 m²' },
        { x: 68, y: 28, w: 32, h: 32, label: 'Bedroom 2', area: '13 m²' },
        { x: 46, y: 24, w: 22, h: 16, label: 'Bath', area: '7 m²' },
        { x: 0, y: 38, w: 26, h: 22, label: 'Study', area: '8 m²' },
        { x: 26, y: 38, w: 42, h: 22, label: 'Entry / Wardrobe', area: '10 m²' },
      ],
      outdoor: [{ x: 0, y: -14, w: 46, h: 14, label: 'Loggia · 11 m²', zone: 'living' }],
    },
  },
  {
    id: '03',
    label: '03',
    num: '03',
    name: 'Travertine Residences',
    kind: 'Three-bedroom residences',
    elevation: '+11.00',
    hour: '16:40',
    light: 'Clear afternoon',
    material: 'Travertine & bronze',
    slice: { x: 876, y: 690, w: 908, h: 125 },
    facade: 'facade-03',
    teaser: '124 m² · 3 bedrooms · terrace · city view',
    intro:
      'Honed travertine underfoot catches the long afternoon sun. A deep terrace frames the Old Town spires across the Daugava — the city held at arm’s length.',
    specs: [
      ['Area', '124 m²'],
      ['Bedrooms', '3'],
      ['Bathrooms', '2'],
      ['Terrace', '22 m²'],
      ['View', 'City & river'],
      ['Residences', '3'],
    ],
    price: 'From €548,000',
    features: ['Deep west terrace', 'Travertine fireplace wall', 'Bronze-framed sliding glass', 'Smoked oak kitchen'],
    palette: [['Travertine', '#cdbb9c'], ['Bronze', '#8f6b45'], ['Smoked oak', '#6b5440'], ['Bouclé', '#ece5d8']],
    zones: [
      { id: 'living', name: 'Living', img: '03-living' },
      { id: 'kitchen', name: 'Kitchen', img: '03-kitchen' },
      { id: 'terrace', name: 'Terrace', img: '03-terrace' },
    ],
    plan: {
      rooms: [
        { x: 0, y: 0, w: 44, h: 36, label: 'Living', area: '38 m²', zone: 'living' },
        { x: 44, y: 0, w: 26, h: 26, label: 'Kitchen / Dining', area: '18 m²', zone: 'kitchen' },
        { x: 70, y: 0, w: 30, h: 26, label: 'Primary suite', area: '19 m²' },
        { x: 70, y: 26, w: 30, h: 20, label: 'Bath', area: '8 m²' },
        { x: 0, y: 36, w: 26, h: 24, label: 'Bedroom 2', area: '13 m²' },
        { x: 26, y: 36, w: 24, h: 24, label: 'Bedroom 3', area: '11 m²' },
        { x: 50, y: 26, w: 20, h: 34, label: 'Entry', area: '9 m²' },
        { x: 70, y: 46, w: 30, h: 14, label: 'Bath 2', area: '6 m²' },
      ],
      outdoor: [{ x: 0, y: -18, w: 70, h: 18, label: 'Terrace · 22 m²', zone: 'terrace' }],
    },
  },
  {
    id: '04',
    label: '04',
    num: '04',
    name: 'Walnut Residences',
    kind: 'Corner residences',
    elevation: '+14.40',
    hour: '19:10',
    light: 'Long summer evening',
    material: 'Walnut & cognac leather',
    slice: { x: 876, y: 545, w: 908, h: 145 },
    facade: 'facade-04',
    teaser: '148 m² · 3 bedrooms · corner river view',
    intro:
      'Two corner residences wrap the building’s west edge. Walnut panelling and cognac leather, and the long, light evenings of a Riga summer — the Old Town across the river, the sun still high at seven.',
    specs: [
      ['Area', '148 m²'],
      ['Bedrooms', '3'],
      ['Bathrooms', '2.5'],
      ['Balcony', '18 m²'],
      ['View', 'Panoramic river'],
      ['Residences', '2'],
    ],
    price: 'From €690,000',
    features: ['Frameless corner glazing', 'Walnut library wall', 'Window seat to the river', 'Dressing room'],
    palette: [['Walnut', '#5a3f2c'], ['Cognac', '#9a5a33'], ['Bronze', '#8f6b45'], ['Sand linen', '#d9c8ad']],
    zones: [
      { id: 'living', name: 'Living', img: '04-living' },
      { id: 'bedroom', name: 'Bedroom', img: '04-bedroom' },
      { id: 'view', name: 'The View', img: '04-view' },
    ],
    plan: {
      rooms: [
        { x: 0, y: 0, w: 46, h: 40, label: 'Corner living', area: '44 m²', zone: 'living' },
        { x: 46, y: 0, w: 24, h: 22, label: 'Kitchen', area: '14 m²' },
        { x: 70, y: 0, w: 30, h: 30, label: 'Primary suite', area: '22 m²', zone: 'bedroom' },
        { x: 46, y: 22, w: 24, h: 18, label: 'Dining', area: '12 m²' },
        { x: 0, y: 40, w: 24, h: 20, label: 'Window seat', area: '', zone: 'view' },
        { x: 24, y: 40, w: 24, h: 20, label: 'Bedroom 2', area: '13 m²' },
        { x: 48, y: 40, w: 22, h: 20, label: 'Bedroom 3', area: '12 m²' },
        { x: 70, y: 30, w: 30, h: 30, label: 'Dressing / Bath', area: '15 m²' },
      ],
      outdoor: [{ x: -14, y: 0, w: 14, h: 60, label: 'Balcony', zone: 'view', vertical: true }],
    },
  },
  {
    id: '05',
    label: '05',
    num: '05',
    name: 'Bronze Residence',
    kind: 'Full-floor premium residence',
    elevation: '+17.80',
    hour: '21:05',
    light: 'Violet dusk',
    material: 'Smoked oak & charcoal',
    slice: { x: 876, y: 405, w: 908, h: 140 },
    facade: 'facade-05',
    teaser: '212 m² · 4 bedrooms · wraparound terrace',
    intro:
      'A single residence occupies the entire floor. Smoked oak, charcoal plaster and a long bronze light line hold the room together as the city starts to glow.',
    specs: [
      ['Area', '212 m²'],
      ['Bedrooms', '4'],
      ['Bathrooms', '3'],
      ['Terrace', '64 m²'],
      ['View', '360° city'],
      ['Residences', '1'],
    ],
    price: '€1,150,000',
    features: ['Wraparound terrace & fire bowl', 'Private lift lobby', 'Chef’s kitchen & pantry', 'Home cinema'],
    palette: [['Smoked oak', '#4a3a2e'], ['Charcoal', '#2f2e2c'], ['Bronze', '#8f6b45'], ['Limestone', '#cfc4b2']],
    zones: [
      { id: 'great', name: 'Great room', img: '05-great' },
      { id: 'terrace', name: 'Terrace', img: '05-terrace' },
    ],
    plan: {
      rooms: [
        { x: 0, y: 0, w: 52, h: 34, label: 'Great room', area: '74 m²', zone: 'great' },
        { x: 52, y: 0, w: 22, h: 24, label: 'Kitchen', area: '18 m²', zone: 'great' },
        { x: 74, y: 0, w: 26, h: 30, label: 'Primary suite', area: '28 m²' },
        { x: 52, y: 24, w: 22, h: 16, label: 'Lift lobby', area: '9 m²' },
        { x: 0, y: 34, w: 24, h: 26, label: 'Bedroom 2', area: '15 m²' },
        { x: 24, y: 34, w: 28, h: 26, label: 'Cinema / Bed 4', area: '16 m²' },
        { x: 52, y: 40, w: 22, h: 20, label: 'Bedroom 3', area: '14 m²' },
        { x: 74, y: 30, w: 26, h: 30, label: 'Dressing / Bath', area: '18 m²' },
      ],
      outdoor: [{ x: -10, y: -12, w: 120, h: 12, label: 'Wraparound terrace · 64 m²', zone: 'terrace' }],
    },
  },
  {
    id: 'ph',
    label: 'PH',
    num: 'PH',
    name: 'Sky House',
    kind: 'Penthouse & roof garden',
    elevation: '+21.20',
    hour: '22:30',
    light: 'Blue hour',
    material: 'Glass, travertine & sky',
    slice: { x: 896, y: 196, w: 868, h: 209 },
    facade: 'facade-ph',
    teaser: '246 m² + 180 m² roof garden · plunge pool',
    intro:
      'A glass pavilion set back on the roof, surrounded by pines and grasses. At blue hour the whole Old Town skyline turns on across the river — the last layer is the sky.',
    specs: [
      ['Area', '246 m²'],
      ['Roof garden', '180 m²'],
      ['Bedrooms', '3'],
      ['Bathrooms', '3.5'],
      ['Pool', '9 × 2.4 m'],
      ['View', 'Old Town skyline'],
    ],
    price: 'Price on request',
    features: ['Glass pavilion living', 'Heated plunge pool', 'Planted roof garden', 'Private lift & stair'],
    palette: [['Travertine', '#d4c7b1'], ['Night glass', '#2e3a4f'], ['Bronze', '#8f6b45'], ['Pine', '#3e4a3a']],
    zones: [
      { id: 'pavilion', name: 'Pavilion', img: 'ph-pavilion' },
      { id: 'pool', name: 'Roof pool', img: 'ph-pool' },
      { id: 'bedroom', name: 'Bedroom', img: 'ph-bedroom' },
    ],
    plan: {
      rooms: [
        { x: 24, y: 8, w: 52, h: 30, label: 'Pavilion', area: '96 m²', zone: 'pavilion' },
        { x: 76, y: 8, w: 24, h: 30, label: 'Primary suite', area: '34 m²', zone: 'bedroom' },
        { x: 24, y: 38, w: 26, h: 16, label: 'Kitchen', area: '22 m²' },
        { x: 50, y: 38, w: 26, h: 16, label: 'Bedrooms 2–3', area: '30 m²' },
        { x: 76, y: 38, w: 24, h: 16, label: 'Baths', area: '20 m²' },
      ],
      outdoor: [
        { x: 0, y: 0, w: 24, h: 62, label: 'Roof garden', zone: 'pool', vertical: true },
        { x: 24, y: 54, w: 76, h: 8, label: 'Plunge pool', zone: 'pool' },
      ],
    },
  },
]

export const NAV = [
  { id: 'project', label: 'Project' },
  { id: 'residences', label: 'Residences' },
  { id: 'architecture', label: 'Architecture' },
  { id: 'location', label: 'Location' },
]

export const img = (name, w = 2400) => `/img/${name}-${w}.webp`
export const srcset = (name) => `/img/${name}-1280.webp 1280w, /img/${name}-2400.webp 2400w`
